# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MRBoardGames' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRBoardGames
  pod 'Socket.IO-Client-Swift', '~> 8.1.2' # Or latest
end
